
[workspace]
resolver = "2"
members = [ "individual_constraint_matching",
    "stress_zero",
]

[workspace.dependencies]
greynet = {path = "../greynet"}

[profile.release]
lto = true
codegen-units = 1
debug = true
opt-level = 3
#rustflags = ["-C", "target-cpu=native"]

