
[workspace]
resolver = "2"
members = [ 
	"individual_constraint_matching",
    "stress_zero",
	"demo_1",
	"demo_2",
]

[workspace.dependencies]
greynet = {path = "../greynet"}

[profile.release]
lto = true
codegen-units = 1
debug = false
opt-level = 3
#rustflags = ["-C", "target-cpu=native"]

