[package]
name = "individual_constraint_matching"
version = "0.1.0"
edition = "2024"

[dependencies]
greynet = {workspace = true}
chrono = "0.4.41"
uuid = "1.17.0"
rand = "0.9.2"
rustc-hash = "2.1.1"
